import { UserProfile, WorkItem, TaskRecord } from "@/types/iso";
import { calculateDefaultDueDate, calculateTaskStatus } from "./date-utils";

export const FALLBACK_USERS: UserProfile[] = [
  {
    id: "nguyethmu@gmail.com",
    fullName: "Đào Thị Nguyệt",
    role: "ADMIN",
    title: "Trưởng khoa",
    email: "nguyethmu@gmail.com",
    phone: "0382337010",
    password: "MeoMoon2789",
    mustChangePassword: false,
    active: true,
  },
  {
    id: "bsluongdinhtrung@gmail.com",
    fullName: "Lương Đình Trung",
    role: "ADMIN",
    title: "Bác sĩ / Quản trị hệ thống",
    email: "bsluongdinhtrung@gmail.com",
    phone: "0900000000",
    password: "MeoMoon2789",
    mustChangePassword: false,
    active: true,
  },
  {
    id: "drtuananh189@gmail.com",
    fullName: "Lê Tuấn Anh",
    role: "USER",
    title: "Bác sĩ",
    email: "drtuananh189@gmail.com",
    phone: "0987372288",
    password: "isogpb@2026",
    mustChangePassword: true,
    active: true,
  },
  {
    id: "nguyenthingan.bsdk@gmail.com",
    fullName: "Nguyễn Thị Ngân",
    role: "USER",
    title: "Bác sĩ",
    email: "nguyenthingan.bsdk@gmail.com",
    phone: "0369239809",
    password: "isogpb@2026",
    mustChangePassword: true,
    active: true,
  },
  {
    id: "thuydung71@gmail.com",
    fullName: "Lương Thị Thùy Dung",
    role: "USER",
    title: "KTV",
    email: "thuydung71@gmail.com",
    phone: "0916787186",
    password: "isogpb@2026",
    mustChangePassword: true,
    active: true,
  },
  {
    id: "funny.monkeyhn345@gmail.com",
    fullName: "Nguyễn Thị Thu Hương",
    role: "USER",
    title: "KTV",
    email: "funny.monkeyhn345@gmail.com",
    phone: "0936099158",
    password: "isogpb@2026",
    mustChangePassword: true,
    active: true,
  },
  {
    id: "tranvanbvdg@gmail.com",
    fullName: "Trần Thị Vân",
    role: "USER",
    title: "KTV",
    email: "tranvanbvdg@gmail.com",
    phone: "0399572155",
    password: "isogpb@2026",
    mustChangePassword: true,
    active: true,
  },
  {
    id: "quangvictor@yahoo.com",
    fullName: "Dương Văn Quang",
    role: "USER",
    title: "KTV",
    email: "quangvictor@yahoo.com",
    phone: "0835028886",
    password: "isogpb@2026",
    mustChangePassword: true,
    active: true,
  },
  {
    id: "laihaiha92@gmail.com",
    fullName: "Lại Hải Hà",
    role: "USER",
    title: "KTV",
    email: "laihaiha92@gmail.com",
    phone: "0988468514",
    password: "isogpb@2026",
    mustChangePassword: true,
    active: true,
  },
];

export const FALLBACK_WORK_ITEMS: WorkItem[] = [
  {
    itemId: "W001",
    itemCode: "XN.QL.01",
    itemName: "Quản lý trang thiết bị",
    assigneeId: "quangvictor@yahoo.com",
    assigneeName: "Dương Văn Quang",
    reviewerId: "nguyethmu@gmail.com",
    reviewerName: "Đào Thị Nguyệt",
    frequency: "Periodic",
    dueRule: "Chốt rà soát trước ngày 05 của tháng kế tiếp",
    reminderDays: 3,
    evidenceRequired: true,
    approvalRequired: false,
    priority: "Cao",
    operationNote: "Theo dõi tình trạng hồ sơ thiết bị/bảo trì/hiệu chuẩn ở cấp tổng hợp, không nhập từng máy.",
    externalLink: "https://quanlithietbi.bstrung.vn",
    active: true,
  },
  {
    itemId: "W002",
    itemCode: "XN.QL.02",
    itemName: "Kiểm soát sự không phù hợp",
    assigneeId: "funny.monkeyhn345@gmail.com",
    assigneeName: "Nguyễn Thị Thu Hương",
    reviewerId: "nguyethmu@gmail.com",
    reviewerName: "Đào Thị Nguyệt",
    frequency: "Event",
    dueRule: "Tạo đầu việc ngay trong ngày phát sinh; cập nhật xử lý trong 24 giờ đầu",
    reminderDays: 0,
    evidenceRequired: true,
    approvalRequired: true,
    priority: "Cao",
    operationNote: "Trưởng khoa cần nhìn được sự cố đang mở/chưa đóng.",
    active: true,
  },
  {
    itemId: "W003",
    itemCode: "XN.QL.03",
    itemName: "Hành động khắc phục (CAPA)",
    assigneeId: "funny.monkeyhn345@gmail.com",
    assigneeName: "Nguyễn Thị Thu Hương",
    reviewerId: "nguyethmu@gmail.com",
    reviewerName: "Đào Thị Nguyệt",
    frequency: "Event",
    dueRule: "Hạn do người tạo/Trưởng khoa đặt; mặc định 14 ngày sau khi mở CAPA",
    reminderDays: 3,
    evidenceRequired: true,
    approvalRequired: true,
    priority: "Cao",
    operationNote: "Cho phép gia hạn có lý do; lưu lịch sử thay đổi hạn.",
    active: true,
  },
  {
    itemId: "W004",
    itemCode: "XN.QL.04",
    itemName: "Xem xét của lãnh đạo",
    assigneeId: "nguyethmu@gmail.com",
    assigneeName: "Đào Thị Nguyệt",
    reviewerId: "nguyethmu@gmail.com",
    reviewerName: "Đào Thị Nguyệt",
    frequency: "Annual",
    dueRule: "Hoàn thành trước 30/11 hằng năm",
    reminderDays: 14,
    evidenceRequired: true,
    approvalRequired: true,
    priority: "Cao",
    operationNote: "Nên cấu hình được ngày cố định theo kế hoạch năm của bệnh viện.",
    active: true,
  },
  {
    itemId: "W005",
    itemCode: "XN.QL.05",
    itemName: "Đào tạo nhân viên",
    assigneeId: "thuydung71@gmail.com",
    assigneeName: "Lương Thị Thùy Dung",
    reviewerId: "nguyethmu@gmail.com",
    reviewerName: "Đào Thị Nguyệt",
    frequency: "Periodic",
    dueRule: "Chốt cập nhật kế hoạch/minh chứng trước ngày 05 của tháng đầu quý sau",
    reminderDays: 5,
    evidenceRequired: true,
    approvalRequired: false,
    priority: "Trung bình",
    operationNote: "Sự kiện đào tạo phát sinh vẫn có thể ghi bổ sung.",
    active: true,
  },
  {
    itemId: "W006",
    itemCode: "XN.QL.06",
    itemName: "Đánh giá tay nghề / năng lực",
    assigneeId: "thuydung71@gmail.com",
    assigneeName: "Lương Thị Thùy Dung",
    reviewerId: "nguyethmu@gmail.com",
    reviewerName: "Đào Thị Nguyệt",
    frequency: "Annual",
    dueRule: "Hoàn thành trước 15/12 hằng năm",
    reminderDays: 14,
    evidenceRequired: true,
    approvalRequired: false,
    priority: "Cao",
    operationNote: "Nếu khoa đánh giá theo ngày vào làm thì IT cần hỗ trợ hạn riêng theo nhân viên.",
    active: true,
  },
  {
    itemId: "W007",
    itemCode: "XN.QL.07",
    itemName: "Xem xét, thỏa thuận dịch vụ",
    assigneeId: "laihaiha92@gmail.com",
    assigneeName: "Lại Hải Hà",
    reviewerId: "nguyethmu@gmail.com",
    reviewerName: "Đào Thị Nguyệt",
    frequency: "Mixed",
    dueRule: "Rà soát định kỳ trước 30/11; phát sinh hợp đồng mới thì theo sự việc",
    reminderDays: 7,
    evidenceRequired: true,
    approvalRequired: false,
    priority: "Trung bình",
    operationNote: "MVP chỉ theo dõi đã rà soát/chưa rà soát.",
    active: true,
  },
  {
    itemId: "W008",
    itemCode: "XN.QL.08",
    itemName: "Lựa chọn và đánh giá nhà cung cấp",
    assigneeId: "quangvictor@yahoo.com",
    assigneeName: "Dương Văn Quang",
    reviewerId: "nguyethmu@gmail.com",
    reviewerName: "Đào Thị Nguyệt",
    frequency: "Annual",
    dueRule: "Hoàn thành trước 30/11 hằng năm",
    reminderDays: 14,
    evidenceRequired: true,
    approvalRequired: false,
    priority: "Trung bình",
    operationNote: "Có thể mở đầu việc phát sinh khi có nhà cung cấp mới.",
    active: true,
  },
  {
    itemId: "W009",
    itemCode: "XN.QL.09",
    itemName: "Giải quyết khiếu nại khách hàng",
    assigneeId: "tranvanbvdg@gmail.com",
    assigneeName: "Trần Thị Vân",
    reviewerId: "nguyethmu@gmail.com",
    reviewerName: "Đào Thị Nguyệt",
    frequency: "Event",
    dueRule: "Tiếp nhận trong ngày; Trưởng khoa đặt hạn xử lý cho từng vụ việc",
    reminderDays: 0,
    evidenceRequired: true,
    approvalRequired: true,
    priority: "Cao",
    operationNote: "Không nên cố định 1 hạn cho mọi khiếu nại.",
    active: true,
  },
  {
    itemId: "W010",
    itemCode: "XN.QL.10",
    itemName: "Kiểm soát môi trường xét nghiệm",
    assigneeId: "tranvanbvdg@gmail.com",
    assigneeName: "Trần Thị Vân",
    reviewerId: "nguyethmu@gmail.com",
    reviewerName: "Đào Thị Nguyệt",
    frequency: "Daily",
    dueRule: "Xác nhận đầu mục hoàn thành trước 09:00 mỗi ngày làm việc",
    reminderDays: 0,
    evidenceRequired: false,
    approvalRequired: false,
    priority: "Cao",
    operationNote: "Chỉ xác nhận 'đã kiểm tra môi trường'.",
    active: true,
  },
  {
    itemId: "W011",
    itemCode: "XN.QL.12",
    itemName: "Quản lý thông tin phòng xét nghiệm",
    assigneeId: "funny.monkeyhn345@gmail.com",
    assigneeName: "Nguyễn Thị Thu Hương",
    reviewerId: "nguyethmu@gmail.com",
    reviewerName: "Đào Thị Nguyệt",
    frequency: "Periodic",
    dueRule: "Rà soát/chốt trước ngày 05 của tháng đầu quý sau",
    reminderDays: 5,
    evidenceRequired: true,
    approvalRequired: false,
    priority: "Trung bình",
    operationNote: "Theo dõi ở mức hồ sơ/chính sách, không thay thế LIS/HIS.",
    active: true,
  },
  {
    itemId: "W012",
    itemCode: "XN.QL.18",
    itemName: "Ngoại kiểm",
    assigneeId: "drtuananh189@gmail.com",
    assigneeName: "Lê Tuấn Anh",
    reviewerId: "nguyethmu@gmail.com",
    reviewerName: "Đào Thị Nguyệt",
    frequency: "Event",
    dueRule: "Hạn theo chương trình ngoại kiểm; nhập Due_Date cho từng đợt",
    reminderDays: 5,
    evidenceRequired: true,
    approvalRequired: false,
    priority: "Cao",
    operationNote: "Cho phép tạo task theo từng đợt, không hard-code lịch.",
    active: true,
  },
  {
    itemId: "W013",
    itemCode: "XN.QL.19",
    itemName: "Quản lý sinh phẩm, vật tư, hóa chất",
    assigneeId: "quangvictor@yahoo.com",
    assigneeName: "Dương Văn Quang",
    reviewerId: "nguyethmu@gmail.com",
    reviewerName: "Đào Thị Nguyệt",
    frequency: "Periodic",
    dueRule: "Chốt rà soát trước ngày 03 của tháng kế tiếp",
    reminderDays: 3,
    evidenceRequired: true,
    approvalRequired: false,
    priority: "Cao",
    operationNote: "Tập trung trạng thái hồ sơ, hạn dùng/tồn kho chi tiết vẫn ở sổ hiện hành.",
    active: true,
  },
  {
    itemId: "W014",
    itemCode: "XN.QL.20",
    itemName: "Đảm bảo tính khách quan",
    assigneeId: "drtuananh189@gmail.com",
    assigneeName: "Lê Tuấn Anh",
    reviewerId: "nguyethmu@gmail.com",
    reviewerName: "Đào Thị Nguyệt",
    frequency: "Mixed",
    dueRule: "Rà soát trước 30/11; cập nhật ngay khi có xung đột lợi ích",
    reminderDays: 14,
    evidenceRequired: true,
    approvalRequired: true,
    priority: "Trung bình",
    operationNote: "Sự việc xung đột lợi ích cần được đẩy lên Trưởng khoa.",
    active: true,
  },
  {
    itemId: "W015",
    itemCode: "XN.QL.22",
    itemName: "Bảo mật thông tin",
    assigneeId: "drtuananh189@gmail.com",
    assigneeName: "Lê Tuấn Anh",
    reviewerId: "nguyethmu@gmail.com",
    reviewerName: "Đào Thị Nguyệt",
    frequency: "Mixed",
    dueRule: "Rà soát trước 30/11; sự cố bảo mật tạo task ngay trong ngày",
    reminderDays: 14,
    evidenceRequired: true,
    approvalRequired: true,
    priority: "Cao",
    operationNote: "Sự cố bảo mật nên được ưu tiên đỏ.",
    active: true,
  },
  {
    itemId: "W016",
    itemCode: "XN.QL.24",
    itemName: "Quản lý rủi ro",
    assigneeId: "tranvanbvdg@gmail.com",
    assigneeName: "Trần Thị Vân",
    reviewerId: "nguyethmu@gmail.com",
    reviewerName: "Đào Thị Nguyệt",
    frequency: "Periodic",
    dueRule: "Chốt rà soát rủi ro trước ngày 05 của tháng đầu quý sau",
    reminderDays: 7,
    evidenceRequired: true,
    approvalRequired: true,
    priority: "Cao",
    operationNote: "Cho phép ghi chú rủi ro mới và hành động xử lý.",
    active: true,
  },
  {
    itemId: "W017",
    itemCode: "XN.QL.25",
    itemName: "Cải tiến liên tục",
    assigneeId: "laihaiha92@gmail.com",
    assigneeName: "Lại Hải Hà",
    reviewerId: "nguyethmu@gmail.com",
    reviewerName: "Đào Thị Nguyệt",
    frequency: "Periodic",
    dueRule: "Chốt tiến độ cải tiến trước ngày 10 của tháng đầu quý sau",
    reminderDays: 7,
    evidenceRequired: true,
    approvalRequired: true,
    priority: "Trung bình",
    operationNote: "Nên có ghi chú kết quả/hiệu quả cải tiến.",
    active: true,
  },
  {
    itemId: "W018",
    itemCode: "XN.QL.26",
    itemName: "Khảo sát sự hài lòng khách hàng",
    assigneeId: "drtuananh189@gmail.com",
    assigneeName: "Lê Tuấn Anh",
    reviewerId: "nguyethmu@gmail.com",
    reviewerName: "Đào Thị Nguyệt",
    frequency: "Periodic",
    dueRule: "Tổng hợp trước ngày 10 của tháng đầu quý sau",
    reminderDays: 7,
    evidenceRequired: true,
    approvalRequired: false,
    priority: "Trung bình",
    operationNote: "Tổng hợp kết quả khảo sát khách hàng định kỳ.",
    active: true,
  },
  {
    itemId: "W019",
    itemCode: "XN.QL.27",
    itemName: "Quản lý hồ sơ",
    assigneeId: "laihaiha92@gmail.com",
    assigneeName: "Lại Hải Hà",
    reviewerId: "nguyethmu@gmail.com",
    reviewerName: "Đào Thị Nguyệt",
    frequency: "Periodic",
    dueRule: "Rà soát tình trạng hồ sơ trước ngày 05 của tháng kế tiếp",
    reminderDays: 3,
    evidenceRequired: false,
    approvalRequired: false,
    priority: "Trung bình",
    operationNote: "Chỉ theo dõi tình trạng đầy đủ/thiếu, không số hóa toàn bộ.",
    active: true,
  },
  {
    itemId: "W020",
    itemCode: "XN.QL.28",
    itemName: "Đánh giá nội bộ",
    assigneeId: "nguyenthingan.bsdk@gmail.com",
    assigneeName: "Nguyễn Thị Ngân",
    reviewerId: "nguyethmu@gmail.com",
    reviewerName: "Đào Thị Nguyệt",
    frequency: "Annual",
    dueRule: "Hoàn thành trước 31/10 hằng năm",
    reminderDays: 14,
    evidenceRequired: true,
    approvalRequired: true,
    priority: "Cao",
    operationNote: "Ngày cụ thể theo kế hoạch đánh giá nội bộ của năm.",
    active: true,
  },
  {
    itemId: "W021",
    itemCode: "XN.QL.29",
    itemName: "Theo dõi và đánh giá bộ chỉ số chất lượng",
    assigneeId: "laihaiha92@gmail.com",
    assigneeName: "Lại Hải Hà",
    reviewerId: "nguyethmu@gmail.com",
    reviewerName: "Đào Thị Nguyệt",
    frequency: "Periodic",
    dueRule: "Chốt số liệu trước ngày 05 của tháng kế tiếp",
    reminderDays: 3,
    evidenceRequired: true,
    approvalRequired: false,
    priority: "Cao",
    operationNote: "Đầu việc xuất hiện nổi bật trên Dashboard hàng tháng.",
    active: true,
  },
  {
    itemId: "W022",
    itemCode: "XN.QL.30",
    itemName: "Quản lý nhân sự",
    assigneeId: "thuydung71@gmail.com",
    assigneeName: "Lương Thị Thùy Dung",
    reviewerId: "nguyethmu@gmail.com",
    reviewerName: "Đào Thị Nguyệt",
    frequency: "Mixed",
    dueRule: "Rà soát cập nhật trước ngày 05 của tháng kế tiếp",
    reminderDays: 3,
    evidenceRequired: true,
    approvalRequired: false,
    priority: "Trung bình",
    operationNote: "Nhân sự mới/nghỉ/đổi vị trí cập nhật ngay khi phát sinh.",
    active: true,
  },
  {
    itemId: "W023",
    itemCode: "XN.QL.31",
    itemName: "Lựa chọn và chuyển gửi mẫu ngoại viện",
    assigneeId: "nguyethmu@gmail.com",
    assigneeName: "Đào Thị Nguyệt",
    reviewerId: "nguyethmu@gmail.com",
    reviewerName: "Đào Thị Nguyệt",
    frequency: "Mixed",
    dueRule: "Sự việc theo hạn từng ca; rà soát tổng hợp trước ngày 05 của tháng đầu quý sau",
    reminderDays: 3,
    evidenceRequired: true,
    approvalRequired: true,
    priority: "Trung bình",
    operationNote: "Người phụ trách đã chốt: Đào Thị Nguyệt.",
    active: true,
  },
  {
    itemId: "W024",
    itemCode: "HT.QL.01",
    itemName: "Kiểm soát tài liệu hệ thống QLCL",
    assigneeId: "laihaiha92@gmail.com",
    assigneeName: "Lại Hải Hà",
    reviewerId: "nguyethmu@gmail.com",
    reviewerName: "Đào Thị Nguyệt",
    frequency: "Mixed",
    dueRule: "Rà soát danh mục hiệu lực trước ngày 05 của tháng kế tiếp",
    reminderDays: 3,
    evidenceRequired: true,
    approvalRequired: false,
    priority: "Cao",
    operationNote: "Tài liệu mới/sửa đổi cập nhật ngay khi ban hành.",
    active: true,
  },
  {
    itemId: "W025",
    itemCode: "GB.QL.02",
    itemName: "Tiếp nhận mẫu Giải phẫu bệnh",
    assigneeId: "thuydung71@gmail.com",
    assigneeName: "Lương Thị Thùy Dung",
    reviewerId: "nguyethmu@gmail.com",
    reviewerName: "Đào Thị Nguyệt",
    frequency: "Daily",
    dueRule: "Xác nhận kiểm soát đầu mục trước 16:30 ngày làm việc",
    reminderDays: 0,
    evidenceRequired: false,
    approvalRequired: false,
    priority: "Trung bình",
    operationNote: "Ghi nhận kiểm soát đầu mục tiếp nhận mẫu hàng ngày.",
    active: true,
  },
  {
    itemId: "W026",
    itemCode: "GB.QL.04",
    itemName: "Báo cáo kết quả Giải phẫu bệnh",
    assigneeId: "thuydung71@gmail.com",
    assigneeName: "Lương Thị Thùy Dung",
    reviewerId: "nguyethmu@gmail.com",
    reviewerName: "Đào Thị Nguyệt",
    frequency: "Periodic",
    dueRule: "Rà soát tình trạng/TAT trước ngày 05 của tháng kế tiếp",
    reminderDays: 3,
    evidenceRequired: true,
    approvalRequired: false,
    priority: "Cao",
    operationNote: "Không thay thế phần mềm trả kết quả.",
    active: true,
  },
  {
    itemId: "W027",
    itemCode: "GB.QL.05",
    itemName: "Lưu mẫu và xử lý mẫu hết thời gian lưu",
    assigneeId: "thuydung71@gmail.com",
    assigneeName: "Lương Thị Thùy Dung",
    reviewerId: "nguyethmu@gmail.com",
    reviewerName: "Đào Thị Nguyệt",
    frequency: "Periodic",
    dueRule: "Rà soát trước ngày 10 của tháng kế tiếp",
    reminderDays: 5,
    evidenceRequired: true,
    approvalRequired: false,
    priority: "Trung bình",
    operationNote: "Có thể dùng link tới biên bản/hồ sơ xử lý.",
    active: true,
  },
  {
    itemId: "W028",
    itemCode: "GB.QL.06-07",
    itemName: "Lưu lam/block và mượn trả",
    assigneeId: "thuydung71@gmail.com",
    assigneeName: "Lương Thị Thùy Dung",
    reviewerId: "nguyethmu@gmail.com",
    reviewerName: "Đào Thị Nguyệt",
    frequency: "Periodic",
    dueRule: "Rà soát trước ngày 05 của tháng kế tiếp",
    reminderDays: 3,
    evidenceRequired: false,
    approvalRequired: false,
    priority: "Trung bình",
    operationNote: "Không quản lý từng lam/block trong MVP.",
    active: true,
  },
  {
    itemId: "W029",
    itemCode: "GB.QL.08",
    itemName: "Nội kiểm",
    assigneeId: "drtuananh189@gmail.com",
    assigneeName: "Lê Tuấn Anh",
    reviewerId: "nguyethmu@gmail.com",
    reviewerName: "Đào Thị Nguyệt",
    frequency: "Periodic",
    dueRule: "Chốt tổng hợp nội kiểm trước ngày 05 của tháng kế tiếp",
    reminderDays: 3,
    evidenceRequired: true,
    approvalRequired: false,
    priority: "Cao",
    operationNote: "Kết quả chi tiết lưu theo hồ sơ nội kiểm hiện hành.",
    externalLink: "https://iso-gpb-duc-giang.vercel.app/",
    active: true,
  },
  {
    itemId: "W030",
    itemCode: "GB.QL.09",
    itemName: "Xác nhận giá trị sử dụng / phê duyệt phương pháp",
    assigneeId: "nguyenthingan.bsdk@gmail.com",
    assigneeName: "Nguyễn Thị Ngân",
    reviewerId: "nguyethmu@gmail.com",
    reviewerName: "Đào Thị Nguyệt",
    frequency: "Event",
    dueRule: "Hạn do Trưởng khoa đặt theo kế hoạch triển khai phương pháp",
    reminderDays: 7,
    evidenceRequired: true,
    approvalRequired: true,
    priority: "Cao",
    operationNote: "Không tạo task định kỳ nếu không có phương pháp mới.",
    externalLink: "https://iso-gpb-duc-giang.vercel.app/",
    active: true,
  },
];

/**
 * Sinh danh sách task mặc định theo kỳ khi Firestore offline hoặc quota exceeded
 */
export function generateFallbackTasks(period: string): TaskRecord[] {
  return FALLBACK_WORK_ITEMS.map((item) => {
    const { dueDate, period: taskPeriod } = calculateDefaultDueDate(item, period);
    const status = calculateTaskStatus(dueDate, undefined, item.reminderDays, item.approvalRequired);
    return {
      taskId: `${item.itemId}_${taskPeriod}`,
      itemId: item.itemId,
      itemCode: item.itemCode,
      itemName: item.itemName,
      period: taskPeriod,
      dueDate,
      assigneeId: item.assigneeId,
      assigneeName: item.assigneeName,
      reviewerId: item.reviewerId,
      reviewerName: item.reviewerName,
      status,
      evidenceRequired: item.evidenceRequired,
      approvalRequired: item.approvalRequired,
      priority: item.priority,
      frequency: item.frequency,
      operationNote: item.operationNote,
      externalLink: item.externalLink,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };
  });
}
